# $Id: Makefile,v 1.1.1.1 2001/03/24 14:55:31 barnykov Exp $

LIBNAME=atccamactools
SRCS = $(wildcard *.c*)

TOPDIR=../..
include $(TOPDIR)/dfmakefiles/defs.make

all:	lib

include $(TOPDIR)/dfmakefiles/rules.make

# $Log: Makefile,v $
# Revision 1.1.1.1  2001/03/24 14:55:31  barnykov
# Переношу в правильный репозиторий...
#
# Revision 1.1  2001/03/24 02:57:46  barnykov
# Иду на Kedr-10.
#
